puzzlebot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  right_wheel_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_to_right_w
    pid: {p: 0.1, i: 2.0, d: 0.0}
  left_wheel_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_to_left_w
    pid: {p: 0.1, i: 2.0, d: 0.0}
