  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  right_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: base_to_right_w
    pid: {p: 0.07, i: 10.0, d: 0.0}
  left_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: base_to_left_w
    pid: {p: 0.07, i: 10.0, d: 0.0}
  
  puzzlebot_controller:
    parameters:
      vel_max: 20.0
      acc_max: 0.2
      L: 0.191
      R: 0.05

    topics:
      cmd_wR: /right_wheel_velocity_controller/command
      cmd_wL: /left_wheel_velocity_controller/command
      pub_wr: /wr
      pub_wl: /wl
      sub_wr: /right_wheel_velocity_controller/state
      sub_wl: /left_wheel_velocity_controller/state
      cmd_vel: /cmd_vel

      
