// Generated by gencpp from file path_planner/AttachObjectResponse.msg
// DO NOT EDIT!


#ifndef PATH_PLANNER_MESSAGE_ATTACHOBJECTRESPONSE_H
#define PATH_PLANNER_MESSAGE_ATTACHOBJECTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace path_planner
{
template <class ContainerAllocator>
struct AttachObjectResponse_
{
  typedef AttachObjectResponse_<ContainerAllocator> Type;

  AttachObjectResponse_()
    : status(false)  {
    }
  AttachObjectResponse_(const ContainerAllocator& _alloc)
    : status(false)  {
  (void)_alloc;
    }



   typedef uint8_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::path_planner::AttachObjectResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::path_planner::AttachObjectResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AttachObjectResponse_

typedef ::path_planner::AttachObjectResponse_<std::allocator<void> > AttachObjectResponse;

typedef boost::shared_ptr< ::path_planner::AttachObjectResponse > AttachObjectResponsePtr;
typedef boost::shared_ptr< ::path_planner::AttachObjectResponse const> AttachObjectResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::path_planner::AttachObjectResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::path_planner::AttachObjectResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::path_planner::AttachObjectResponse_<ContainerAllocator1> & lhs, const ::path_planner::AttachObjectResponse_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::path_planner::AttachObjectResponse_<ContainerAllocator1> & lhs, const ::path_planner::AttachObjectResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace path_planner

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::path_planner::AttachObjectResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::path_planner::AttachObjectResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path_planner::AttachObjectResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path_planner::AttachObjectResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_planner::AttachObjectResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_planner::AttachObjectResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::path_planner::AttachObjectResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a1255d4d998bd4d6585c64639b5ee9a";
  }

  static const char* value(const ::path_planner::AttachObjectResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a1255d4d998bd4dULL;
  static const uint64_t static_value2 = 0x6585c64639b5ee9aULL;
};

template<class ContainerAllocator>
struct DataType< ::path_planner::AttachObjectResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "path_planner/AttachObjectResponse";
  }

  static const char* value(const ::path_planner::AttachObjectResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::path_planner::AttachObjectResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool status\n"
"\n"
;
  }

  static const char* value(const ::path_planner::AttachObjectResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::path_planner::AttachObjectResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AttachObjectResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::path_planner::AttachObjectResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::path_planner::AttachObjectResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PATH_PLANNER_MESSAGE_ATTACHOBJECTRESPONSE_H
