// Generated by gencpp from file path_planner/AttachObject.msg
// DO NOT EDIT!


#ifndef PATH_PLANNER_MESSAGE_ATTACHOBJECT_H
#define PATH_PLANNER_MESSAGE_ATTACHOBJECT_H

#include <ros/service_traits.h>


#include <path_planner/AttachObjectRequest.h>
#include <path_planner/AttachObjectResponse.h>


namespace path_planner
{

struct AttachObject
{

typedef AttachObjectRequest Request;
typedef AttachObjectResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AttachObject
} // namespace path_planner


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::path_planner::AttachObject > {
  static const char* value()
  {
    return "1f7ad086a1f8f6cd5178c1472fed0d33";
  }

  static const char* value(const ::path_planner::AttachObject&) { return value(); }
};

template<>
struct DataType< ::path_planner::AttachObject > {
  static const char* value()
  {
    return "path_planner/AttachObject";
  }

  static const char* value(const ::path_planner::AttachObject&) { return value(); }
};


// service_traits::MD5Sum< ::path_planner::AttachObjectRequest> should match
// service_traits::MD5Sum< ::path_planner::AttachObject >
template<>
struct MD5Sum< ::path_planner::AttachObjectRequest>
{
  static const char* value()
  {
    return MD5Sum< ::path_planner::AttachObject >::value();
  }
  static const char* value(const ::path_planner::AttachObjectRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::path_planner::AttachObjectRequest> should match
// service_traits::DataType< ::path_planner::AttachObject >
template<>
struct DataType< ::path_planner::AttachObjectRequest>
{
  static const char* value()
  {
    return DataType< ::path_planner::AttachObject >::value();
  }
  static const char* value(const ::path_planner::AttachObjectRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::path_planner::AttachObjectResponse> should match
// service_traits::MD5Sum< ::path_planner::AttachObject >
template<>
struct MD5Sum< ::path_planner::AttachObjectResponse>
{
  static const char* value()
  {
    return MD5Sum< ::path_planner::AttachObject >::value();
  }
  static const char* value(const ::path_planner::AttachObjectResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::path_planner::AttachObjectResponse> should match
// service_traits::DataType< ::path_planner::AttachObject >
template<>
struct DataType< ::path_planner::AttachObjectResponse>
{
  static const char* value()
  {
    return DataType< ::path_planner::AttachObject >::value();
  }
  static const char* value(const ::path_planner::AttachObjectResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PATH_PLANNER_MESSAGE_ATTACHOBJECT_H
