// Generated by gencpp from file path_planner/AttachObjectRequest.msg
// DO NOT EDIT!


#ifndef PATH_PLANNER_MESSAGE_ATTACHOBJECTREQUEST_H
#define PATH_PLANNER_MESSAGE_ATTACHOBJECTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace path_planner
{
template <class ContainerAllocator>
struct AttachObjectRequest_
{
  typedef AttachObjectRequest_<ContainerAllocator> Type;

  AttachObjectRequest_()
    : action(false)
    , frame()  {
    }
  AttachObjectRequest_(const ContainerAllocator& _alloc)
    : action(false)
    , frame(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _action_type;
  _action_type action;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _frame_type;
  _frame_type frame;





  typedef boost::shared_ptr< ::path_planner::AttachObjectRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::path_planner::AttachObjectRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AttachObjectRequest_

typedef ::path_planner::AttachObjectRequest_<std::allocator<void> > AttachObjectRequest;

typedef boost::shared_ptr< ::path_planner::AttachObjectRequest > AttachObjectRequestPtr;
typedef boost::shared_ptr< ::path_planner::AttachObjectRequest const> AttachObjectRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::path_planner::AttachObjectRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::path_planner::AttachObjectRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::path_planner::AttachObjectRequest_<ContainerAllocator1> & lhs, const ::path_planner::AttachObjectRequest_<ContainerAllocator2> & rhs)
{
  return lhs.action == rhs.action &&
    lhs.frame == rhs.frame;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::path_planner::AttachObjectRequest_<ContainerAllocator1> & lhs, const ::path_planner::AttachObjectRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace path_planner

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::path_planner::AttachObjectRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::path_planner::AttachObjectRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path_planner::AttachObjectRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path_planner::AttachObjectRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_planner::AttachObjectRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_planner::AttachObjectRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::path_planner::AttachObjectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4146cef4fd7f8a49ebf08b4dcc63292f";
  }

  static const char* value(const ::path_planner::AttachObjectRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4146cef4fd7f8a49ULL;
  static const uint64_t static_value2 = 0xebf08b4dcc63292fULL;
};

template<class ContainerAllocator>
struct DataType< ::path_planner::AttachObjectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "path_planner/AttachObjectRequest";
  }

  static const char* value(const ::path_planner::AttachObjectRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::path_planner::AttachObjectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool action\n"
"string frame\n"
;
  }

  static const char* value(const ::path_planner::AttachObjectRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::path_planner::AttachObjectRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action);
      stream.next(m.frame);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AttachObjectRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::path_planner::AttachObjectRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::path_planner::AttachObjectRequest_<ContainerAllocator>& v)
  {
    s << indent << "action: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.action);
    s << indent << "frame: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.frame);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PATH_PLANNER_MESSAGE_ATTACHOBJECTREQUEST_H
