// Generated by gencpp from file path_planner/RequestGoal.msg
// DO NOT EDIT!


#ifndef PATH_PLANNER_MESSAGE_REQUESTGOAL_H
#define PATH_PLANNER_MESSAGE_REQUESTGOAL_H

#include <ros/service_traits.h>


#include <path_planner/RequestGoalRequest.h>
#include <path_planner/RequestGoalResponse.h>


namespace path_planner
{

struct RequestGoal
{

typedef RequestGoalRequest Request;
typedef RequestGoalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RequestGoal
} // namespace path_planner


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::path_planner::RequestGoal > {
  static const char* value()
  {
    return "c3bc436f69c66a775d9ac3090d41bd75";
  }

  static const char* value(const ::path_planner::RequestGoal&) { return value(); }
};

template<>
struct DataType< ::path_planner::RequestGoal > {
  static const char* value()
  {
    return "path_planner/RequestGoal";
  }

  static const char* value(const ::path_planner::RequestGoal&) { return value(); }
};


// service_traits::MD5Sum< ::path_planner::RequestGoalRequest> should match
// service_traits::MD5Sum< ::path_planner::RequestGoal >
template<>
struct MD5Sum< ::path_planner::RequestGoalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::path_planner::RequestGoal >::value();
  }
  static const char* value(const ::path_planner::RequestGoalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::path_planner::RequestGoalRequest> should match
// service_traits::DataType< ::path_planner::RequestGoal >
template<>
struct DataType< ::path_planner::RequestGoalRequest>
{
  static const char* value()
  {
    return DataType< ::path_planner::RequestGoal >::value();
  }
  static const char* value(const ::path_planner::RequestGoalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::path_planner::RequestGoalResponse> should match
// service_traits::MD5Sum< ::path_planner::RequestGoal >
template<>
struct MD5Sum< ::path_planner::RequestGoalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::path_planner::RequestGoal >::value();
  }
  static const char* value(const ::path_planner::RequestGoalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::path_planner::RequestGoalResponse> should match
// service_traits::DataType< ::path_planner::RequestGoal >
template<>
struct DataType< ::path_planner::RequestGoalResponse>
{
  static const char* value()
  {
    return DataType< ::path_planner::RequestGoal >::value();
  }
  static const char* value(const ::path_planner::RequestGoalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PATH_PLANNER_MESSAGE_REQUESTGOAL_H
