// Generated by gencpp from file path_planner/RequestGoalRequest.msg
// DO NOT EDIT!


#ifndef PATH_PLANNER_MESSAGE_REQUESTGOALREQUEST_H
#define PATH_PLANNER_MESSAGE_REQUESTGOALREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace path_planner
{
template <class ContainerAllocator>
struct RequestGoalRequest_
{
  typedef RequestGoalRequest_<ContainerAllocator> Type;

  RequestGoalRequest_()
    : action()  {
    }
  RequestGoalRequest_(const ContainerAllocator& _alloc)
    : action(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _action_type;
  _action_type action;





  typedef boost::shared_ptr< ::path_planner::RequestGoalRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::path_planner::RequestGoalRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RequestGoalRequest_

typedef ::path_planner::RequestGoalRequest_<std::allocator<void> > RequestGoalRequest;

typedef boost::shared_ptr< ::path_planner::RequestGoalRequest > RequestGoalRequestPtr;
typedef boost::shared_ptr< ::path_planner::RequestGoalRequest const> RequestGoalRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::path_planner::RequestGoalRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::path_planner::RequestGoalRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::path_planner::RequestGoalRequest_<ContainerAllocator1> & lhs, const ::path_planner::RequestGoalRequest_<ContainerAllocator2> & rhs)
{
  return lhs.action == rhs.action;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::path_planner::RequestGoalRequest_<ContainerAllocator1> & lhs, const ::path_planner::RequestGoalRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace path_planner

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::path_planner::RequestGoalRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::path_planner::RequestGoalRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path_planner::RequestGoalRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path_planner::RequestGoalRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_planner::RequestGoalRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_planner::RequestGoalRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::path_planner::RequestGoalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7757aad79fa343e61bc69ed7f1b7666d";
  }

  static const char* value(const ::path_planner::RequestGoalRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7757aad79fa343e6ULL;
  static const uint64_t static_value2 = 0x1bc69ed7f1b7666dULL;
};

template<class ContainerAllocator>
struct DataType< ::path_planner::RequestGoalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "path_planner/RequestGoalRequest";
  }

  static const char* value(const ::path_planner::RequestGoalRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::path_planner::RequestGoalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string action\n"
;
  }

  static const char* value(const ::path_planner::RequestGoalRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::path_planner::RequestGoalRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RequestGoalRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::path_planner::RequestGoalRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::path_planner::RequestGoalRequest_<ContainerAllocator>& v)
  {
    s << indent << "action: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.action);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PATH_PLANNER_MESSAGE_REQUESTGOALREQUEST_H
